language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  #- python backup.py
  - coverage run scheduled-jobs-on-off.py

after_success:
- codecov
